# This file is shared across all environments:
# * on linux workstations the shortcut M-Esc is bound to:
#     toggle-window -n fullscreen-terminal \
#       -c "gnome-terminal --full-screen --hide-menubar \
#       --working-directory=~ -t fullscreen-terminal -e \
#       'env FULLSCREEN_TERMINAL=y zsh'"
#   and normal terminal run windowed without \
#   FULLSCREEN_TERMINAL being set.
# * on linux servers the shell variable $SSH_TTY is non-empty.
# * on osx the shortcut M-Esc is bound to a fullscreen
#   instance of iTerm2 (still need to find a way to set
#   FULLSCREEN_TERMINAL in that setup).

# For OS specific configurations
OS=$(uname -s)

# Set the PATH
PATH=/sbin:/bin
for p in /usr/bin /usr/sbin /usr/local/bin /usr/local/sbin /opt/local/bin /opt/local/sbin ~/usr/bin; do
  [ -d $p ] && PATH=$p:$PATH
done
export PATH

# Fix SSH_AUTH_SOCK when called from gnome shortcut key
# See https://bugzilla.redhat.com/show_bug.cgi?id=713955
if [ "$OS" = "Linux" ]; then
  SSH_AUTH_SOCK=`netstat -xl | grep -o '/tmp/keyring-.*/ssh$'`
  [ -n "$SSH_AUTH_SOCK" ] && export SSH_AUTH_SOCK
fi

# Should we start tmux?
# Values of ZSH_USE_TMUX:
# * 0: don't start tmux
# * 1: attach to first deattached tmux, or create new one
# * 2: attach to first tmux (multiple clients share same tmux)
if [[ -n "$SSH_TTY" ]]; then
    ZSH_USE_TMUX=2
elif [[ -n "$FULLSCREEN_TERMINAL" ]]; then
    ZSH_USE_TMUX=1
else
    ZSH_USE_TMUX=0
fi

# Start tmux (if not already started)
if [[ -z "$TMUX" && $ZSH_USE_TMUX > 0 ]]; then
  if [[ $ZSH_USE_TMUX = 2 ]]; then
    tmux_shared 'shared' && exit $?
  elif [[ $ZSH_USE_TMUX = 1 ]]; then
    if tmux ls 2> /dev/null | grep -v '(attached)$' > /dev/null; then
      tmux attach && exit $?
    else
      tmux -2 && exit $?
    fi
  fi
fi

# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Path to override the default ZSH custom directory
ZSH_CUSTOM=$(dirname $(realpath ${ZDOTDIR-~}/.zshrc))/custom

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="sgeb"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal
# title.
# Do no update title if on linux and outside tmux, needed for the
# system-wide console hotkey (xdotool checks the window title)
[[ "$OS" = "Linux" && -z "$TMUX" ]] && DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git git-flow extract)

# OS specific plugins
[[ "$OS" = "Linux" ]] && plugins+=(sgeb-apt)
[[ "$OS" = "Darwin" ]] && plugins+=(brew) #(osx mate)

source $ZSH/oh-my-zsh.sh

# Set colors for ls
[[ "$OS" == "Linux" ]] && export LS_COLORS="di=34;40:ln=35;40:so=32;40:pi=33;40:ex=31;40:bd=34;46:cd=34;43:su=0;41:sg=0;46:tw=0;42:ow=0;43:"
[[ "$OS" == "Darwin" ]] && export LSCOLORS="exfxcxdxbxegedabagacad"

# Matlab variables for OSX
if [ "$OS" = "Darwin" ]; then
  export MATLABROOT="/Applications/MATLAB_R2011a.app"
  export DYLD_LIBRARY_PATH="$MATLABROOT/runtime/maci64:$MATLABROOT/bin/maci64:$MATLABROOT/sys/os/maci64:"
  export XAPPLRESDIR="$MATLABROOT/X11/app-defaults"
fi

