# For OS specific configurations
OS=$(uname -s)

# Should we start tmux?
[[ "$OS" = "Linux" && -n "$FULLSCREEN_TERMINAL" ]] && ZSH_USE_TMUX=yes

# Start tmux
if [ -n "$ZSH_USE_TMUX" ]; then
  if [ -z "$TMUX" ]; then
    if tmux ls 2> /dev/null | grep -v '(attached)$'; then
        tmux attach && exit 0
    else
        tmux -2 && exit 0
    fi
  fi
fi

# Set the PATH
export PATH=~/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# Fix SSH_AUTH_SOCK when called from gnome shortcut key
# See https://bugzilla.redhat.com/show_bug.cgi?id=713955
if [ "$OS" = "Linux" ]; then
  SSH_AUTH_SOCK=`netstat -xl | grep -o '/tmp/keyring-.*/ssh$'`
  [ -n "$SSH_AUTH_SOCK" ] && export SSH_AUTH_SOCK
fi


# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Path to override the default ZSH custom directory
ZSH_CUSTOM=$(dirname $(realpath ${ZDOTDIR-~}/.zshrc))/custom

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="robbyrussell"
#ZSH_THEME="blinks"
ZSH_THEME="kphoen"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal
# title.
# Do no update title if on linux and outside tmux, needed for the
# system-wide console hotkey (xdotool checks the window title)
[[ "$OS" = "Linux" && -z "$TMUX" ]] && DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git git-flow extract)

# OS specific plugins
[[ "$OS" = "Linux" ]] && plugins+=(sgeb-apt)
#[[ "$OS" = "Darwin" ]] && plugins+=(osx mate)

source $ZSH/oh-my-zsh.sh
